rednext1/TextEditor

TextEditor/Form1.Designer.cs, TextEditor/Form1.cs, TextEditor/Form1.resx, TextEditor/Properties/Resources.Designer.cs, TextEditor/Properties/Resources.resx
Functions for opening a file and saving. Also auxiliary verification functions. Added 2 more buttons (Undo-Redo)
=> Add Function Open and Save. Add button Undo-Redo

TextEditor/Form1.Designer.cs, TextEditor/Form1.cs, TextEditor/Form1.resx
Implemented and added the function of opening the latest files with the ability to save the list in an external file
Done:
-Save open file to list and external file function
-Function of Loading an open file to the list from an external file
-Realisation of file opening by clicking in the drop-down menu
=> Implemented and added the function of opening the latest files

TextEditor/Form1.Designer.cs, TextEditor/Form1.cs, TextEditor/Form1.resx
Added features: document change tracking, column and row counting. Fixed grammatical errors
=> Added features: document change tracking, column and row counting

TextEditor/Form1.Designer.cs, TextEditor/Form1.cs, TextEditor/Form1.resx
Added functionality to style and font buttons
=> Added functionality to style and font buttons

TextEditor/Form1.cs
Adding functions for working with the file, save as a new document.
=> Adding  functions  save as, new document

TextEditor/Form1.cs
=>  Development of Undo-Redo

TextEditor/Form1.Designer.cs, TextEditor/Form1.cs, TextEditor/Form1.resx
=> Adding tabs

TextEditor/Form1.Designer.cs, TextEditor/Form1.cs, TextEditor/Form1.resx
Added a drop-down test menu with commands. For File and Edit
=> Added a drop-down test menu with commands. For File and Edit

TextEditor/Form1.Designer.cs, TextEditor/Form1.cs, TextEditor/Form1.resx
Added a function that will allow opening documents by dragging a file to the editor window (Drag & Drop) and a function trackBar_Zoom_Scroll
=> Added a function 

TextEditor/Properties/Resources.Designer.cs, TextEditor/Properties/Resources.resx
=> Correction of the resource folder

TextEditor/Form1.Designer.cs, TextEditor/Form1.cs, TextEditor/Form1.resx
For correct operation, the string passed to the function has been changed
=> Change function lists

TextEditor/Form1.cs
New toolStripButton_list_Click
=> New toolStripButton_list_Click

TextEditor/Form1.cs
Removed unnecessary processing
=> change toolStripButton_list_Click

TextEditor/Form1.Designer.cs, TextEditor/Form1.resx, TextEditor/TextEditor.csproj
Interface ergonomics has been improved:
- Fixed: print icon was not copied to resource files
- Zoom Display Label was repositioned correctly.
=> Interface ergonomics has been improved. Fixed print icon.

TextEditor/Form1.cs
=> SendKeys.Flush();

TextEditor/Form1.cs
There was a floating problem with inserting Lists. Possible solution: specify window descriptor exactly where to use keyboard shortcut (ctrl+shift+L).
=> Improvement of the Function to insert lists.

TextEditor/Form1.cs
Finish version toolStripButton_list_Click
=> Finish version toolStripButton_list_Click

TextEditor/Form1.cs
Fihish toolStripButton_list_Click
=> Fihish toolStripButton_list_Click

TextEditor/Form1.Designer.cs, TextEditor/Form1.cs, TextEditor/Form1.resx
The cursor position is now displayed when the mouse is clicked in the text
=> Improved function for displaying cursor position in text

TextEditor/Form1.cs
Improved function for remembering the last opened files. Now files that were opened via Drag n Drop are remembered.
=> Improved function for remembering the last opened files
